package com.demo.community.model;

public class LikeComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKE_COMMENT.ID
     *
     * @mbg.generated Sat Mar 28 20:19:49 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKE_COMMENT.LIKER_ID
     *
     * @mbg.generated Sat Mar 28 20:19:49 CST 2020
     */
    private Long likerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKE_COMMENT.COMMENT_ID
     *
     * @mbg.generated Sat Mar 28 20:19:49 CST 2020
     */
    private Long commentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKE_COMMENT.ID
     *
     * @return the value of LIKE_COMMENT.ID
     *
     * @mbg.generated Sat Mar 28 20:19:49 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKE_COMMENT.ID
     *
     * @param id the value for LIKE_COMMENT.ID
     *
     * @mbg.generated Sat Mar 28 20:19:49 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKE_COMMENT.LIKER_ID
     *
     * @return the value of LIKE_COMMENT.LIKER_ID
     *
     * @mbg.generated Sat Mar 28 20:19:49 CST 2020
     */
    public Long getLikerId() {
        return likerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKE_COMMENT.LIKER_ID
     *
     * @param likerId the value for LIKE_COMMENT.LIKER_ID
     *
     * @mbg.generated Sat Mar 28 20:19:49 CST 2020
     */
    public void setLikerId(Long likerId) {
        this.likerId = likerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKE_COMMENT.COMMENT_ID
     *
     * @return the value of LIKE_COMMENT.COMMENT_ID
     *
     * @mbg.generated Sat Mar 28 20:19:49 CST 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKE_COMMENT.COMMENT_ID
     *
     * @param commentId the value for LIKE_COMMENT.COMMENT_ID
     *
     * @mbg.generated Sat Mar 28 20:19:49 CST 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }
}