package com.demo.community.model;

public class LikeComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKE_COMMENT.id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKE_COMMENT.liker_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long likerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKE_COMMENT.comment_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long commentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKE_COMMENT.id
     *
     * @return the value of LIKE_COMMENT.id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKE_COMMENT.id
     *
     * @param id the value for LIKE_COMMENT.id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKE_COMMENT.liker_id
     *
     * @return the value of LIKE_COMMENT.liker_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getLikerId() {
        return likerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKE_COMMENT.liker_id
     *
     * @param likerId the value for LIKE_COMMENT.liker_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setLikerId(Long likerId) {
        this.likerId = likerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKE_COMMENT.comment_id
     *
     * @return the value of LIKE_COMMENT.comment_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKE_COMMENT.comment_id
     *
     * @param commentId the value for LIKE_COMMENT.comment_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }
}