package com.demo.community.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.notifier_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long notifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.receiver_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.outer_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long outerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.type
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.gmt_create
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.status
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.notifier_name
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private String notifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTIFICATION.outer_title
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private String outerTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.id
     *
     * @return the value of NOTIFICATION.id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.id
     *
     * @param id the value for NOTIFICATION.id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.notifier_id
     *
     * @return the value of NOTIFICATION.notifier_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getNotifierId() {
        return notifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.notifier_id
     *
     * @param notifierId the value for NOTIFICATION.notifier_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setNotifierId(Long notifierId) {
        this.notifierId = notifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.receiver_id
     *
     * @return the value of NOTIFICATION.receiver_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.receiver_id
     *
     * @param receiverId the value for NOTIFICATION.receiver_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.outer_id
     *
     * @return the value of NOTIFICATION.outer_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.outer_id
     *
     * @param outerId the value for NOTIFICATION.outer_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setOuterId(Long outerId) {
        this.outerId = outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.type
     *
     * @return the value of NOTIFICATION.type
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.type
     *
     * @param type the value for NOTIFICATION.type
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.gmt_create
     *
     * @return the value of NOTIFICATION.gmt_create
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.gmt_create
     *
     * @param gmtCreate the value for NOTIFICATION.gmt_create
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.status
     *
     * @return the value of NOTIFICATION.status
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.status
     *
     * @param status the value for NOTIFICATION.status
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.notifier_name
     *
     * @return the value of NOTIFICATION.notifier_name
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public String getNotifierName() {
        return notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.notifier_name
     *
     * @param notifierName the value for NOTIFICATION.notifier_name
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setNotifierName(String notifierName) {
        this.notifierName = notifierName == null ? null : notifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTIFICATION.outer_title
     *
     * @return the value of NOTIFICATION.outer_title
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTIFICATION.outer_title
     *
     * @param outerTitle the value for NOTIFICATION.outer_title
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle == null ? null : outerTitle.trim();
    }
}