package com.demo.community.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.title
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.gmt_create
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.gmt_modified
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.creator_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.comment_count
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.view_count
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.like_count
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.tag
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.description
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.id
     *
     * @return the value of QUESTION.id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.id
     *
     * @param id the value for QUESTION.id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.title
     *
     * @return the value of QUESTION.title
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.title
     *
     * @param title the value for QUESTION.title
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.gmt_create
     *
     * @return the value of QUESTION.gmt_create
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.gmt_create
     *
     * @param gmtCreate the value for QUESTION.gmt_create
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.gmt_modified
     *
     * @return the value of QUESTION.gmt_modified
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.gmt_modified
     *
     * @param gmtModified the value for QUESTION.gmt_modified
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.creator_id
     *
     * @return the value of QUESTION.creator_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.creator_id
     *
     * @param creatorId the value for QUESTION.creator_id
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.comment_count
     *
     * @return the value of QUESTION.comment_count
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.comment_count
     *
     * @param commentCount the value for QUESTION.comment_count
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.view_count
     *
     * @return the value of QUESTION.view_count
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.view_count
     *
     * @param viewCount the value for QUESTION.view_count
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.like_count
     *
     * @return the value of QUESTION.like_count
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.like_count
     *
     * @param likeCount the value for QUESTION.like_count
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.tag
     *
     * @return the value of QUESTION.tag
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.tag
     *
     * @param tag the value for QUESTION.tag
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.description
     *
     * @return the value of QUESTION.description
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.description
     *
     * @param description the value for QUESTION.description
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}