package com.demo.community.mapper;

import com.demo.community.model.AuthUser;
import com.demo.community.model.AuthUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AuthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    long countByExample(AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    int deleteByExample(AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    int insert(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    int insertSelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    List<AuthUser> selectByExampleWithRowbounds(AuthUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    List<AuthUser> selectByExample(AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    AuthUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") AuthUser record, @Param("example") AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    int updateByExample(@Param("record") AuthUser record, @Param("example") AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    int updateByPrimaryKeySelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER
     *
     * @mbg.generated Fri Apr 03 18:54:45 CST 2020
     */
    int updateByPrimaryKey(AuthUser record);
}